
; Project Configuration File for PlatformIO

[platformio]
; default_envs = p4_16mb
default_envs = p4_16mb_debug
src_dir = ./esp32p4_arduino_mipi-dsi_lvgl


[common]
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.30-1/platform-espressif32.zip
;; 3.30 throws 
; platform = https://github.com/pioarduino/platform-espressif32.git#55.03.30
platform = https://github.com/pioarduino/platform-espressif32.git#53.03.13+github
framework = arduino
board_build.filesystem = fatfs


[env:p4_16mb]
extends = common
board = esp32-p4-evboard
board_build.psram = enabled
board_build.flash_size = 16MB
board_build.partitions = custom-tinyuf2-partitions-16MB-noota.csv
monitor_speed = 115200
lib_extra_dirs = lvgl
lib_deps = 
    adafruit/Adafruit TinyUSB Library
; lib_ldf_mode = deep
build_flags =
    -DTINYUSB_CDC_ENABLED=1
    -DARDUINO_USB_CDC_ON_BOOT=1


[env:p4]
extends = common
board = esp32-p4
board_build.psram = enabled
board_build.flash_size = 16MB
board_build.partitions = custom-tinyuf2-partitions-16MB-noota.csv
board_build.f_cpu = 360000000L
board_build.flash_mode = qio
monitor_speed = 115200
lib_extra_dirs = lvgl
lib_deps = 
    adafruit/Adafruit TinyUSB Library
; lib_ldf_mode = deep
build_flags =
    -DTINYUSB_CDC_ENABLED=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DUSB_CDC_ON_BOOT=1



; Debug targets:

[env:p4_16mb_debug]
extends = common
board = esp32-p4-evboard
monitor_speed = 115200
lib_extra_dirs = lvgl
lib_deps = 
    adafruit/Adafruit TinyUSB Library
board_build.partitions = custom-tinyuf2-partitions-16MB-noota.csv
board_build.psram = enabled
board_build.flash_size = 16MB
; lib_ldf_mode = deep
; build_type = debug
; debug_tool = esp-builtin
; debug_init_break = tbreak setup
; build_flags = -DDEBUG -DCORE_DEBUG_LEVEL=5 -DCONFIG_LOG_DEFAULT_LEVEL=5 -DESP_LOG_LEVEL=5 -
; debug_build_flags = -Og -ggdb3 -fno-inline-functions -fno-inline -fno-inline-small-functions -fno-inline-functions-called-once -fno-inline-functions-called-once-optimized -fno-inline-small-functions-called-once
build_type = debug
debug_tool = jlink
debug_init_break = tbreak setup
build_flags =
    -DDEBUG
    -DCORE_LOG_LEVEL=5
    -DARDUINO_LOG_LEVEL=5
    -DESP_LOG_LEVEL=5
    -g3
    -Og
    -fno-inline
    -fno-omit-frame-pointer
    -DTINYUSB_CDC_ENABLED=1
    -DARDUINO_USB_CDC_ON_BOOT=1
debug_build_flags =
    -Og
    -ggdb3
    -fno-inline-functions
    -fno-inline
    -fno-inline-small-functions
    -fno-inline-functions-called-once

[env:p4_debug]
extends = common
board = esp32-p4
board_build.flash_size = 16MB
board_build.psram = enabled
; board_build.partition = default
board_build.partitions = custom-tinyuf2-partitions-16MB-noota.csv
board_build.f_cpu = 360000000L
board_build.flash_mode = qio
monitor_speed = 115200
lib_extra_dirs = lvgl
lib_deps = 
    adafruit/Adafruit TinyUSB Library
; lib_ldf_mode = deep
build_type = debug
debug_tool = jlink
debug_init_break = tbreak setup
build_flags =
    -Iesp32p4_arduino_mipi-dsi_lvgl/src/touch/gt911_touch.cpp
    -Isrc/touch/gt911_touch.cpp
    -DDEBUG
    -DCORE_LOG_LEVEL=5
    -DARDUINO_LOG_LEVEL=5
    -DESP_LOG_LEVEL=5
    ; -Og
    ; -g3
    ; -ggdb3
    ; -fno-inline-functions
    ; -fno-inline
    ; -fno-inline-small-functions
    ; -fno-inline-functions-called-once
    ; -fno-omit-frame-pointer
    -DTINYUSB_CDC_ENABLED=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DUSB_CDC_ON_BOOT=1